/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#e3d8cc",
        outline: "#747878",
        "inverse-on-surface": "#faefe3",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#281801",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed": "#e4e2e1",
        "text-muted": "#6B6B6B",
        "on-primary-container": "#949393",
        tertiary: "#241500",
        "on-error-container": "#93000a",
        "secondary-fixed": "#fcdeba",
        "on-surface-variant": "#444748",
        "tertiary-fixed": "#feddb3",
        "surface-container": "#f7ece0",
        "background-alt": "#F5F2E1",
        "inverse-primary": "#c8c6c5",
        primary: "#171818",
        "surface-container-highest": "#ece1d5",
        "surface-bright": "#fff8f3",
        "outline-variant": "#c4c7c7",
        "secondary-container": "#f9dbb7",
        surface: "#E8DDD1",
        "on-primary": "#ffffff",
        "on-secondary-container": "#755f42",
        "on-primary-fixed": "#1b1c1c",
        secondary: "#715b3e",
        "on-tertiary-container": "#ab8f6a",
        background: "#E8DDD1",
        "on-tertiary-fixed-variant": "#584324",
        "surface-variant": "#ece1d5",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed-dim": "#dfc29f",
        "inverse-surface": "#352f27",
        "tertiary-container": "#3b290c",
        "surface-container-low": "#fdf2e5",
        "on-background": "#201b14",
        "on-secondary-fixed": "#281903",
        "surface-container-high": "#f2e6da",
        "surface-container-lowest": "#ffffff",
        "surface-cream": "#E8DDD1",
        "primary-container": "#2c2c2c",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-fixed-variant": "#574329",
        "on-surface": "#201b14",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#e1c299",
        charcoal: "#2C2C2C",
        "warm-taupe": "#8B7355",
        "soft-sand": "#C9A58E",
        // Matches lib/theme.ts in the mobile app — the shared accent/
        // success colour across both platforms. Added here because v4
        // components (HeroV4, Welcome) were already using bg-sage before
        // this existed on the website, silently rendering transparent.
        sage: "#A8B5A4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "component-padding": "16px",
        "stack-sm": "8px",
        "section-gap": "80px",
        "container-max": "1200px",
        gutter: "24px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-h1": ["Inter"],
        "body-strong": ["Inter"],
        "headline-h1-mobile": ["Inter"],
        "headline-h2": ["Inter"],
        "label-sm": ["Inter"],
        "body-main": ["Inter"],
        "tagline-handwritten": ["Playfair Display"],
        "headline-h3": ["Inter"],
        "micro-eyebrow": ["Inter"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Playfair Display"],
      },
      fontSize: {
        "headline-h1": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-strong": ["16px", { lineHeight: "1.6", fontWeight: "600" }],
        "headline-h1-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-h2": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-main": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "tagline-handwritten": ["18px", { lineHeight: "1.5", letterSpacing: "0.1em", fontWeight: "400" }],
        "headline-h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "micro-eyebrow": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
